### ISSUE TITLE
Add reference to the original cube

### ISSUE THREAD

**Issue by zeginis** [OpenGovIntelligence/json-qb#15]
It is usefull at the table format to have a link to the original cube. This will enable applications to switch between slices. 
For example if an application visualizes a slice with specific `free_dimensions` and  `locked_dimensions`, then having the link to the original cube will enable the application to directly get another slice with different `free_dimensions` and  `locked_dimensions`.

**Comment by RickMoynihan** [comment]
The `@id` link at the top level should be the URI of the `qb:Dataset` instance itself, so I think this is already in the format.
