### ISSUE TITLE
Rename total_cells to total_observations

### ISSUE THREAD

**Issue by zeginis** [OpenGovIntelligence/json-qb#18]
- The `total_cells` is part of the pagination information. We could consider moving it under `ext:pagination`
- In case of sparce data (see #16) the null values will be part of the `total_cells` count?
- At the Single Cell Values the `total_cells` should be 1. At the example there is a typo:  `"total_cells": 31,  "cell": 2311`.

**Comment by RickMoynihan** [comment]
You raise a good point about sparseness - `total_cells` was originally named `total_observations` but I changed it to match the tabular/spreadsheet terminology elsewhere.  Will rename it back from `total_cells` to `total_observations` for clarity and to avoid the sparseness problem you mention.

I'll rename `cell` to `observation` too.

**Comment by RickMoynihan** [comment]
BTW @zeginis if you spot typos as with the value of `total_cells` if you have time would it be possible for you please issue PR's to fix them?

Thanks.

**Comment by zeginis** [comment]
@RickMoynihan  yes sure I can fix them directly.
