### ISSUE TITLE
Related project

### ISSUE THREAD

**Issue by csarven** [OpenGovIntelligence/json-qb#8]
See related project https://json-stat.org/ for interoperability, borrow ideas, merge efforts, or minimise duplicate effort if any.

**Comment by BillSwirrl** [comment]
Thanks Sarven - we have been reviewing json-stat in detail to see how best we can incorporate or build on their work.  Our current (early stage) thinking is that we should offer an API route that returns a json-stat representation a slice of a cube.

**Comment by RickMoynihan** [comment]
Thanks I've added a section to the documentation covering json-stat...  Closing this issue for now as it's not really an issue with the proposal.
